name: bity
version: 0.1.0
description: Library for communicating with the Bity API.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bity

dependencies:
    http: ^0.12.0+1

dev_dependencies:
    test: ^1.3.4
    mock_web_server: ^4.0.0

environment:
    sdk: ">=2.0.0 <3.0.0"
