name: bity
version: 0.3.5
description: Minimalistic library for communicating with the Bity API v2.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bity_client

dependencies:
    http: ^0.12.1
    iban: ^0.2.0

dev_dependencies:
    test: ^1.3.4
    mock_web_server: ^4.0.0
    pedantic: ^1.9.0

environment:
    sdk: ">=2.1.0 <3.0.0"
